#!/usr/bin/env python3
"""Generate unique zen captions for all images in feeds.json"""

import json
import random

# Large pool of unique zen titles (100+)
ZEN_TITLES = [
    "Morning Dew", "Silent Dawn", "Gentle Breeze", "Moonlit Path", "Quiet Stream",
    "Ancient Wisdom", "Floating Clouds", "Still Waters", "Empty Sky", "Soft Light",
    "Distant Mountains", "Bamboo Grove", "Stone Garden", "Autumn Leaf", "Spring Rain",
    "Winter Snow", "Summer Heat", "Fading Twilight", "Rising Sun", "Setting Moon",
    "Wandering Mind", "Grounded Heart", "Open Spirit", "Clear Vision", "Pure Essence",
    "Infinite Space", "Timeless Moment", "Sacred Pause", "Deep Roots", "High Branches",
    "River Song", "Wind Whisper", "Earth Breath", "Fire Dance", "Water Mirror",
    "Mountain Silence", "Valley Echo", "Forest Dream", "Desert Bloom", "Ocean Calm",
    "Starlit Night", "Sunlit Morning", "Clouded Noon", "Rainy Evening", "Misty Dawn",
    "Golden Hour", "Blue Moment", "Green Shade", "White Peace", "Dark Wisdom",
    "First Step", "Last Breath", "New Beginning", "Old Teaching", "Simple Truth",
    "Hidden Path", "Open Door", "Closed Eyes", "Listening Heart", "Speaking Silence",
    "Walking Meditation", "Sitting Still", "Standing Tall", "Lying Down", "Rising Up",
    "Letting Be", "Holding Space", "Finding Center", "Losing Self", "Becoming Whole",
    "Before Thought", "After Words", "Beyond Time", "Within Space", "Through Darkness",
    "Into Light", "Around Corners", "Between Moments", "Under Stars", "Over Mountains",
    "Gentle Awakening", "Soft Landing", "Slow Unfolding", "Quick Insight", "Deep Knowing",
    "Surface Ripples", "Hidden Depths", "Outer Form", "Inner Essence", "True Nature",
    "Original Face", "Beginner Mind", "Master Touch", "Student Heart", "Teacher Silence",
    "Borrowed Time", "Given Moment", "Taken Breath", "Left Behind", "Carried Forward",
    "Crescent Moon", "Full Circle", "Half Light", "Quarter Turn", "Complete Stillness",
    "Broken Pattern", "Mended Heart", "Torn Veil", "Sewn Together", "Woven Peace",
    "Painted Sky", "Carved Stone", "Sculpted Wind", "Written Water", "Spoken Earth",
    "Unspoken Bond", "Unseen Hand", "Unheard Song", "Unfelt Touch", "Unknown Path",
    "Remembered Dream", "Forgotten Word", "Lost Thought", "Found Treasure", "Kept Secret",
    "Shared Wisdom", "Private Joy", "Public Peace", "Common Ground", "Rare Moment",
    "Daily Practice", "Nightly Rest", "Weekly Pause", "Monthly Turn", "Yearly Cycle",
    "Eternal Now", "Fleeting Beauty", "Lasting Peace", "Passing Cloud", "Remaining Light",
    "Growing Edge", "Shrinking Fear", "Expanding Love", "Contracting Ego", "Balanced Center",
    "Harmonious Flow", "Discordant Note", "Melodic Breath", "Rhythmic Heart", "Silent Song",
    "Visible Breath", "Invisible Hand", "Tangible Peace", "Intangible Joy", "Palpable Calm",
    "Rough Edge", "Smooth Stone", "Sharp Mind", "Dull Pain", "Bright Awareness",
    "Dim Memory", "Clear Present", "Foggy Past", "Sunny Future", "Cloudy Now",
    "Warm Embrace", "Cool Distance", "Hot Passion", "Cold Reason", "Temperate Balance",
    "Dry Wit", "Wet Earth", "Dusty Road", "Clean Slate", "Muddy Waters",
    "Fresh Start", "Stale Ending", "Sweet Release", "Bitter Lesson", "Salty Tear",
    "Heavy Heart", "Light Spirit", "Dense Fog", "Thin Air", "Thick Silence",
    "Wide Open", "Narrow Path", "Long Journey", "Short Rest", "Tall Order",
    "Small Wonder", "Big Picture", "Little Joy", "Great Peace", "Minor Key",
    "Major Shift", "Natural State", "Artificial Calm", "Organic Growth", "Synthetic Peace",
    "Raw Beauty", "Cooked Wisdom", "Ripe Moment", "Green Youth", "Golden Age",
    "Silver Lining", "Bronze Medal", "Iron Will", "Steel Resolve", "Copper Glow",
    "Paper Thin", "Rock Solid", "Sand Soft", "Water Fluid", "Air Light"
]

# Large pool of unique zen summaries (200+)
ZEN_SUMMARIES = [
    "In stillness, the world reveals its secrets.",
    "Each moment holds infinite possibility.",
    "Breathe in peace, breathe out worry.",
    "The path appears when you stop searching.",
    "Silence speaks louder than words.",
    "Let go of what no longer serves you.",
    "Find the extraordinary in the ordinary.",
    "Your presence is your greatest gift.",
    "Wisdom grows in the garden of patience.",
    "The mind follows where attention leads.",
    "Peace begins with a single breath.",
    "In simplicity, find true abundance.",
    "The journey inward has no end.",
    "Nature teaches without speaking.",
    "Every ending births a beginning.",
    "Rest in the space between thoughts.",
    "Your true self needs no improvement.",
    "Acceptance opens every door.",
    "The present moment is always enough.",
    "Find freedom in letting things be.",
    "Clarity comes when the mind settles.",
    "The heart knows what the mind forgets.",
    "In solitude, discover your true companion.",
    "Gratitude transforms what you have into enough.",
    "The universe speaks in whispers.",
    "Balance is found in accepting imbalance.",
    "Your inner light needs no external fuel.",
    "Time slows when presence deepens.",
    "The answer lies in the question itself.",
    "Peace is not found but uncovered.",
    "Every breath is a fresh start.",
    "The deepest truths are the simplest.",
    "In emptiness, find fullness.",
    "Your thoughts are clouds, not the sky.",
    "The body holds wisdom the mind overlooks.",
    "Surrender is not giving up but opening up.",
    "The observer is never disturbed.",
    "In the gap between stimulus and response lies freedom.",
    "What you seek is seeking you.",
    "The mountain does not move to meet the clouds.",
    "Awareness is the first step to change.",
    "In chaos, find your still point.",
    "The flower does not compete with the one beside it.",
    "Your essence remains untouched by experience.",
    "The river never steps in the same place twice.",
    "In darkness, the stars become visible.",
    "Trust the timing of your life.",
    "The seed does not know the flower it will become.",
    "In waiting, practice being.",
    "Your breath is always in the present.",
    "The wave is never separate from the ocean.",
    "In softness, find your strength.",
    "The moon does not fight the night.",
    "Your presence heals more than your words.",
    "In letting go, we receive.",
    "The tree grows strongest against the wind.",
    "Your inner peace is not dependent on outer conditions.",
    "In the ordinary, find the sacred.",
    "The drop contains the whole ocean.",
    "Your attention is your most precious resource.",
    "In stillness, movement is understood.",
    "The bamboo bends but does not break.",
    "Your thoughts are visitors, not residents.",
    "In the pause, wisdom speaks.",
    "The candle loses nothing by lighting another.",
    "Your true nature is unshakeable.",
    "In acceptance, transformation begins.",
    "The lotus grows in mud but blooms unstained.",
    "Your inner compass always points home.",
    "In the beginning is the end, and vice versa.",
    "The bell rings once but its sound lingers.",
    "Your awareness is always awake.",
    "In unity, diversity flourishes.",
    "The stone at rest holds immense energy.",
    "Your breath connects inner and outer worlds.",
    "In the present, past and future meet.",
    "The bird does not tire of the sky.",
    "Your heart is larger than any pain.",
    "In emptying the cup, we fill it again.",
    "The root supports the flower silently.",
    "Your being is more important than your doing.",
    "In each face, see the universal.",
    "The mirror reflects without judgment.",
    "Your peace is not someone else's to give.",
    "In the question, find the teaching.",
    "The pond reflects when undisturbed.",
    "Your life is the expression of your consciousness.",
    "In surrender, find your power.",
    "The wind moves without leaving tracks.",
    "Your experience is uniquely yours.",
    "In impermanence, find freedom.",
    "The moon waxes and wanes without complaint.",
    "Your center holds when the periphery spins.",
    "In connection, isolation dissolves.",
    "The fire transforms what it touches.",
    "Your gratitude multiplies your blessings.",
    "In patience, the fruit ripens naturally.",
    "The earth supports all beings equally.",
    "Your compassion begins with yourself.",
    "In silence, hear what cannot be spoken.",
    "Look deeply and see clearly.",
    "The rain falls without choosing where.",
    "Where there is patience, there is peace.",
    "The gentle touch opens what force cannot.",
    "True strength flows from inner stillness.",
    "Behind every cloud, the sun still shines.",
    "The mind that is not fixated is always fresh.",
    "Each difficulty carries its own teaching.",
    "The space between notes makes the music.",
    "Contentment is the greatest wealth.",
    "The leaf falls without knowing where it lands.",
    "In giving, we receive more than we give.",
    "The stream finds its way around obstacles.",
    "Awareness needs no improvement.",
    "The sunrise asks nothing of the day.",
    "In each moment, a lifetime of learning.",
    "The mountain remains unmoved by praise or blame.",
    "Let your actions be your teachings.",
    "The shadow proves the presence of light.",
    "In the heart of difficulty lies opportunity.",
    "The full moon illuminates without effort.",
    "What is left when you stop trying to become?",
    "The kite rises highest against the wind.",
    "In attachment, we lose what we cling to.",
    "The echo returns what was sent.",
    "Your nature is peace itself.",
    "The oak sleeps in the acorn.",
    "In the midst of movement, find stillness.",
    "The horizon is always receding yet always present.",
    "What we resist persists.",
    "The spring knows when to burst forth.",
    "In every arrival, a departure awaits.",
    "The night is darkest before dawn.",
    "Your light cannot be diminished.",
    "The roots drink in darkness to bloom in light.",
    "In forgetting ourselves, we find ourselves.",
    "The frost disappears with the morning sun.",
    "Every sound returns to silence.",
    "The caterpillar does not know it will fly.",
    "In each breath, the universe begins anew.",
    "The mountain lake reflects what is above.",
    "Truth needs no defense.",
    "The tea cools whether we watch or not.",
    "In releasing control, we gain true power.",
    "The seasons change without asking permission.",
    "Your awareness has no edges.",
    "The fish does not feel the weight of water.",
    "In every ending, seeds of beginning.",
    "The star shines without knowing who sees.",
    "What you do with love, you do well.",
    "The rain does not judge where it falls.",
    "In the eye of the storm, find calm.",
    "The flower opens in its own time.",
    "Your true face was there before your parents met.",
    "The snow melts, the river swells.",
    "In acknowledging shadow, we expand light.",
    "The bridge connects without choosing sides.",
    "Every step is a arrival.",
    "The mist hides and reveals equally.",
    "In the gap between breaths, eternity waits.",
    "The flame dances without rehearsing.",
    "Your depth cannot be measured.",
    "The bamboo is hollow but strong.",
    "In welcoming all, resistance fades.",
    "The cloud does not carry yesterday's rain.",
    "Simplicity is the ultimate sophistication.",
    "The stone teaches patience without words.",
    "In each failure, a hidden gift.",
    "The tide ebbs and flows without effort.",
    "Your heart beats without being asked.",
    "The pearl forms around irritation.",
    "In solitude, find connection with all.",
    "The butterfly remembers being a caterpillar.",
    "What appears solid is mostly space.",
    "The thunder follows lightning obediently.",
    "In serving others, we serve ourselves.",
    "The dew disappears but water remains.",
    "Your true home is not a place.",
    "The spider weaves without a plan.",
    "In the ordinary cup, extraordinary tea.",
    "The mountain stream finds the sea eventually.",
    "Observation changes what is observed.",
    "The pine tree does not envy the cherry blossom.",
    "In loss, discover what cannot be lost.",
    "The full bowl cannot receive.",
    "Your silence speaks volumes.",
    "The ink dries but the meaning lives.",
    "In every face, recognize your own.",
    "The geese fly south without maps.",
    "What blooms also fades, and that is beautiful.",
    "The single candle lights a thousand others.",
    "In confusion, clarity gestates.",
    "The pebble creates ripples far beyond itself.",
    "Your light reaches further than you know.",
    "The ant carries more than its weight.",
    "In attachment, we lose what we grasp.",
    "The winter tree is not dead, only resting.",
    "Every wall is also a door.",
    "The morning dew vanishes but nourishes first.",
    "In the crack, the light enters.",
    "The empty vessel makes the loudest sound.",
    "Your journey and destination are one.",
    "The wind knows no boundaries.",
    "In the ancient, find the new.",
    "The moon has no light of its own yet illuminates.",
    "Your reflection is not you.",
    "The tree does not hurry yet completes itself.",
    "In the darkness, trust your feet.",
    "The sand shifts but the beach remains.",
    "Your thoughts are not commands.",
    "The waterfall does not pause to rest.",
    "In each ending, gratitude waits.",
    "The fog lifts when the sun is ready.",
    "Your fears are teachers in disguise.",
    "The rock is shaped by what flows around it.",
    "In repetition, find variation.",
    "The stars guided travelers for millennia.",
    "Your story is still being written.",
    "The wave returns to the sea willingly.",
    "In the bitter, taste the sweet.",
    "The compass points but does not walk.",
    "Your struggles build your strengths.",
    "The cocoon is not a prison.",
    "In the shallow, the depth hides.",
    "The echo carries the original voice.",
    "Your past is a lesson, not a life sentence.",
    "The horizon calls but never demands.",
    "In the noise, silence persists.",
    "The lake holds the sky without grasping.",
    "Your kindness returns multiplied.",
    "The branch bends so the tree survives.",
    "In the familiar, discover the unknown.",
    "The footprint fades but the journey continues.",
    "Your inner weather changes like the outer.",
    "The valley receives what the mountain releases.",
    "In the temporary, find the eternal.",
    "The sunrise has never once been late.",
    "Your roots grow deeper in drought.",
    "The well gives without ever emptying.",
    "In the chaos, patterns emerge.",
    "The flame needs the darkness to be seen.",
    "Your awareness is broader than your focus.",
    "The fruit falls when it is ready.",
    "In the conflict, harmony is born.",
    "The river does not remember every stone.",
    "Your breath connects you to all that breathes.",
    "The shadow changes with the light source.",
    "In the small gesture, great meaning lives.",
    "The bird sings without an audience.",
    "Your presence changes every room you enter.",
    "The storm clears the air.",
    "In the wound, the medicine hides.",
    "The root drinks what the leaves cannot see.",
    "Your attention is a gift you give freely.",
    "The dewdrop contains the whole morning.",
    "In the ending, the beginning sleeps.",
    "The stone does not need to prove its solidity.",
    "Your silence is sometimes the best answer.",
    "The spider rebuilds without complaint.",
    "In the pause between notes, music breathes.",
    "The mountain views all seasons equally.",
    "Your intention shapes your experience.",
    "The snake sheds its skin to grow.",
    "In the forgetting, remembering becomes precious.",
    "The tide returns regardless of the shore.",
    "Your peace is not dependent on understanding.",
    "The fire transforms but also illuminates.",
    "In the old, the new takes root.",
    "The moon rises whether witnessed or not.",
    "Your center holds what the edges lose.",
    "The seed knows nothing of the flower.",
    "In the waiting, strength gathers.",
    "The path is made by walking.",
    "Your heart beats without instruction.",
    "The cloud does not strain to float.",
    "In each inhale, the universe expands.",
    "The shell surrenders its pearl slowly.",
    "Your journey has no wrong turns.",
    "The frost adorns what it touches.",
    "In the quiet, answers form.",
    "The owl sees what daylight hides.",
    "Your wisdom grows in the dark soil of difficulty.",
    "The wave does not fight the shore.",
    "In the breaking, the light enters.",
    "The pine stands straight through the storm.",
    "Your true face has no age.",
    "The river accepts all tributaries.",
    "In the giving, receiving is born.",
    "The stone polishes the stone.",
    "Your thoughts pass like clouds in an empty sky.",
    "The morning remembers nothing of the night.",
    "In the depth, find your buoyancy.",
    "The flower does not hold yesterday's fragrance.",
    "Your breath is always beginning again.",
    "The frost retreats before the sun.",
    "In the fall, the rise begins.",
    "The drop of water shapes the stone over time.",
    "Your stillness speaks to those who listen.",
    "The bamboo sways but returns to center.",
    "In the simple act, profound meaning resides.",
    "The caterpillar trusts the process.",
    "Your light casts shadows you may never see.",
    "The rain does not choose favorites.",
    "In the night, rest prepares action.",
    "The dust settles when stirring stops.",
    "Your heart knows the way forward.",
    "The lake stills itself without trying.",
    "In the reflection, truth hides in plain sight.",
    "The bridge asks nothing of those who cross.",
    "Your silence holds more than words can carry.",
    "The seed breaks open to become itself.",
    "In the unplanned, the authentic emerges.",
    "The snow falls equally on all paths.",
    "Your awareness touches what it observes.",
    "The cup holds what is poured into it.",
    "In the space between, connection lives.",
    "The mountain teaches without a single word.",
    "Your presence is the present.",
    "The wind writes and erases on sand.",
    "In the routine, find the ritual.",
    "The star shines from unfathomable distance.",
    "Your stillness invites stillness.",
    "The rain feeds the roots you cannot see.",
    "In the breath, find your anchor.",
    "The sun sets without sadness.",
    "Your light needs no permission to shine.",
    "The pebble rests at the bottom of the stream.",
    "In the melting, new forms emerge.",
    "The tree stands where the seed fell.",
    "Your path is yours alone to walk.",
    "The dawn comes without being summoned.",
    "In the ordinary moment, the sacred waits.",
    "The leaf does not rush to fall.",
    "Your peace extends beyond your body.",
    "The stream finds the sea eventually.",
    "In the listening, the speaker is heard.",
    "The flame gives light by consuming itself.",
    "Your compassion begins where judgment ends.",
    "The wind passes through without leaving.",
    "In the space you hold, others find room.",
    "The stone warms slowly and cools slowly.",
    "Your inner garden grows with attention.",
    "The moon wanes only to wax again.",
    "In the imperfect, find perfection.",
    "The rain does not discriminate.",
    "Your breath is your constant companion.",
    "The forest grows in its own time.",
    "In the unfinished, completion waits.",
    "The dawn knows nothing of yesterday's dusk.",
    "Your peace cannot be taken, only abandoned.",
    "The river carries what falls into it.",
    "In the fracture, wholeness reveals itself.",
    "The bell has no memory of its last ring.",
    "Your awareness outlasts all that it witnesses.",
    "The stone requires nothing to be complete.",
    "In the mundane, the magnificent hides.",
    "The tide turns without announcement.",
    "Your essence needs nothing added.",
    "The branch holds the snow until it's ready.",
    "In the cold, warmth is appreciated.",
    "The leaf lands where the wind decides.",
    "Your true nature shines through all conditions.",
    "The well does not chase those who thirst.",
    "In the letting go, new hands appear.",
    "The stars need no arrangement.",
    "Your inner compass points true.",
    "The morning mist knows when to lift.",
    "In the descent, the ascent is born.",
    "The candle does not fear its own light.",
    "Your attention is your most powerful tool.",
    "The shore does not resist the tide.",
    "In the present, all time exists.",
    "The seed does not doubt the flower within.",
    "Your stillness touches the stillness of others.",
    "The rain returns to the sky.",
    "In the softening, strength reveals itself.",
    "The mountain does not lean toward the valley.",
    "Your heart opens when you let it.",
    "The sunset paints without a brush.",
    "In the letting be, becoming happens.",
    "The river knows no rush, only flow.",
    "Your presence is the best present.",
    "The flower blooms for itself alone.",
    "In the shadow, the light is remembered.",
    "The wind carries seeds it will never see grow.",
    "Your inner stillness creates outer calm.",
    "The lake accepts the rain drop by drop.",
    "In the waiting, growth occurs.",
    "The tree does not compare itself to the mountain.",
    "Your journey is your destination.",
    "The fog parts for those who walk through it.",
    "In the simplicity, all complexity resolves.",
    "The sun needs no instruction to rise.",
    "Your peace is always available.",
    "The rain washes without judgment.",
    "In the breath, eternity visits.",
    "The stone rests content in itself.",
    "Your true home is always with you.",
    "The flower turns toward what nourishes it.",
    "In the unspoken, understanding grows.",
    "The moonlight needs no praise.",
    "Your awareness cannot be diminished.",
    "The stream speaks in many voices.",
    "In the old paths, new discoveries wait.",
    "The hawk circles without hurry.",
    "Your patience is its own reward.",
    "The dewdrop reflects the entire sky.",
    "In the acceptance, peace arrives.",
    "The night embraces all equally.",
    "Your light illuminates your own path.",
    "The tree draws from invisible depths.",
    "In the release, freedom is found.",
    "The wave returns what it borrowed.",
    "Your nature is already complete.",
    "The sky holds all weather without preference.",
    "In the quiet mind, wisdom speaks.",
    "The stone smooths over countless tides.",
    "Your breath teaches patience.",
    "The path reveals itself one step at a time.",
    "In the darkness, inner light emerges.",
    "The rain nourishes what it cannot see.",
    "Your stillness is a gift to the world.",
    "The bird trusts the air beneath its wings.",
    "In the surrender, victory is found.",
    "The moon guides without commanding.",
    "Your presence is the meditation.",
    "The river does not mourn what it leaves behind.",
    "In the pause, purpose clarifies.",
    "The flame dances with whatever wind comes.",
    "Your awareness is the sky, not the clouds.",
    "The earth turns without asking permission.",
    "In the solitude, connection deepens.",
    "The stone teaches permanence to the water.",
    "Your inner peace radiates outward.",
    "The seed waits for its moment.",
    "In the yielding, strength appears.",
    "The horizon exists only in perception.",
    "Your heart beats in rhythm with all hearts.",
    "The bamboo grows empty and strong.",
    "In the returning, departure is forgotten.",
    "The water reflects what stands before it.",
    "Your true nature cannot be lost.",
    "The wind bows to nothing yet moves all.",
    "In the simple breath, the universe expands.",
    "The mountain summit is just the beginning.",
    "Your inner landscape shapes the outer.",
    "The tide follows its own schedule.",
    "In the acceptance of what is, peace resides.",
    "The moon does not hurry across the sky.",
    "Your stillness is revolutionary.",
    "The rain has no preference for petals or stones.",
    "In the ordinary lies the extraordinary.",
    "The tree grows toward light without knowing why.",
    "Your compassion heals more than words.",
    "The stream carries reflections without attachment.",
    "In the breath between breaths, eternity waits.",
    "The snow falls in its own perfect silence.",
    "Your inner peace needs no explanation.",
    "The flower unfolds according to its own rhythm.",
    "In the storm, the eye remains still.",
    "The stone at the bottom of the river is content.",
    "Your true nature shines when you stop hiding.",
    "The dawn comes whether we witness it or not.",
    "In the small moments, the big picture lives.",
    "The mountain holds both the climber and the path.",
    "Your awareness illuminates all that it touches.",
    "The river has no opinion about its direction.",
    "In the stillness before action, wisdom gathers.",
    "The tide trusts its rhythm.",
    "Your light is needed exactly as it is.",
    "The seed surrenders its shell to become itself.",
    "In the empty space, all possibility exists.",
    "The rain accepts every path downward.",
    "Your breath knows exactly what to do.",
    "The mountain neither reaches up nor holds back.",
    "In the acceptance of impermanence, peace settles.",
    "The flame needs no instruction to give warmth.",
    "Your inner compass always points home.",
    "The leaf falls when ready, not when told.",
    "In the question lies the beginning of wisdom.",
    "The stream finds its way around every obstacle.",
    "Your stillness creates ripples of calm.",
    "The sun sets without looking back.",
    "In the darkness, we learn to trust our feet.",
    "The bamboo bows to the snow then springs back.",
    "Your true path cannot be taken from you.",
    "The rain does not judge where it falls.",
    "In the ordinary cup, extraordinary tea.",
    "The stone needs no movement to be whole.",
    "Your inner light cannot be extinguished.",
    "The tide responds to forces we cannot see.",
    "In the ending, new beginnings are planted.",
    "The moon illuminates without diminishing.",
    "Your presence changes everything around it.",
    "The stream speaks without words.",
    "In the breath, the universe knows itself.",
    "The hawk rides the wind without effort.",
    "Your awareness is wider than your thoughts.",
    "The snow melts when ready, not when told.",
    "In the pause, all answers wait.",
    "The stone at peace attracts peace.",
    "Your journey shapes you as you shape it.",
    "The rain returns the ocean's gift to the mountain.",
    "In the stillness, movement is understood.",
    "The flower blooms without seeking attention.",
    "Your inner garden flourishes with attention.",
    "The bamboo grove sings in the wind.",
    "In the shadow, the light's source is confirmed.",
    "The stone warms slowly, cools slowly, teaches patience.",
    "Your true self is always present.",
    "The stream accepts the rain without comment.",
    "In the exhale, the inhale is prepared.",
    "The mountain's summit is also its foot.",
    "Your stillness speaks louder than action.",
    "The dawn comes without announcement.",
    "In the simplicity, all complexity finds home.",
    "The rain nourishes without asking for thanks.",
    "Your awareness is the silent witness to all.",
    "The tide ebbs to flow again.",
    "In the old, the new is already present.",
    "The flame needs the darkness to be appreciated.",
    "Your breath connects you to all that lives.",
    "The river carries no memory of yesterday.",
    "In the pause, clarity arrives.",
    "The stone accepts its place without complaint.",
    "Your inner peace is portable.",
    "The moon rises without effort.",
    "In the acceptance of mystery, wisdom begins.",
    "The tree reaches up and down simultaneously.",
    "Your true nature requires no defense.",
    "The rain falls without keeping score.",
    "In the listening, the speaker finds voice.",
    "The stone smooths under the patient stream.",
    "Your stillness is your greatest action.",
    "The cloud drifts without destination.",
    "In the unknown, all discovery waits.",
    "The starlight we see has traveled ages.",
    "Your thoughts are not facts.",
    "The river meets all bridges equally.",
    "In the mundane task, practice presence.",
    "The soil holds what the tree cannot carry alone.",
    "Your intention precedes your action.",
    "The bell's sound exists only in the moment.",
    "In the repetition, find renewal.",
    "The frost writes temporary poems.",
    "Your true wealth is your attention.",
    "The branch that bends survives the storm.",
    "In the formless, all forms arise.",
    "The tea knows nothing of the ceremony.",
    "Your silence is a form of speech.",
    "The fish does not fear the water.",
    "In the letting go, you receive.",
    "The stone does not envy the bird.",
    "Your awareness outlasts any thought.",
    "The rain accepts the path downhill.",
    "In the center, the edges are understood.",
    "The flame does not burn itself.",
    "Your inner teacher waits patiently.",
    "The wave's power comes from the ocean.",
    "In the chaos, your breath remains.",
    "The horizon is always exactly where you are.",
    "Your peace cannot be outsourced.",
    "The seed's power is in its patience.",
    "In the familiar, see with fresh eyes.",
    "The moon reflects the sun without knowing.",
    "Your true self needs no introduction.",
    "The river divides to reunite.",
    "In the storm, find the stillness within.",
    "The candle does not fear its end.",
    "Your light reaches farther than you see.",
    "The mountain holds all paths equally.",
    "In the breaking open, beauty is revealed.",
    "The snowflake is complete in itself.",
    "Your breath is older than any worry.",
    "The earth spins without your attention.",
    "In the uncertainty, possibility thrives.",
    "The spider web glistens with morning light.",
    "Your peace is the foundation of all action.",
    "The lake does not refuse any reflection.",
    "In the ordinary step, the journey unfolds.",
    "The bird does not worry about tomorrow's song.",
    "Your presence is medicine.",
    "The stone at the crossroads points nowhere.",
    "In the return, the departure is completed.",
    "The flame illuminates what it consumes.",
    "Your inner world shapes the outer.",
    "The rain falls up in evaporation.",
    "In the small, the infinite resides.",
    "The fog is just a cloud that came down.",
    "Your awareness has no location.",
    "The tree's shadow is always attached.",
    "In the transition, both worlds exist.",
    "The pebble's splash ripples outward forever.",
    "Your stillness is louder than any noise.",
    "The night sky holds infinite depths.",
    "In the ending, begin again.",
    "The breeze carries what it cannot hold.",
    "Your center is always available.",
    "The creek shapes itself to the land.",
    "In the waiting room of life, practice peace.",
    "The echo proves the canyon's depth.",
    "Your light does not diminish in sharing.",
    "The seed breaks to become the tree.",
    "In the obvious, the hidden truth lives.",
    "The tide has no memory of retreat.",
    "Your true home is in this breath.",
    "The mountain needs no one to witness it.",
    "In the gap between worlds, wisdom speaks.",
    "The rain drop contains the whole ocean.",
    "Your inner sun never sets.",
    "The branch holds the sky up close.",
    "In the fading light, new colors appear.",
    "The stone skips only when released.",
    "Your breath arrives without being called."
]

def generate_unique_feeds():
    # Load existing feeds
    with open('feeds.json', 'r') as f:
        feeds = json.load(f)
    
    # Shuffle and extend pools if needed
    titles = ZEN_TITLES.copy()
    summaries = ZEN_SUMMARIES.copy()
    
    # Ensure we have enough unique combinations
    total_images = len(feeds)
    print(f"Total images to process: {total_images}")
    print(f"Available titles: {len(titles)}")
    print(f"Available summaries: {len(summaries)}")
    
    # Extend titles if needed by adding numbered variants
    while len(titles) < total_images:
        base = random.choice(ZEN_TITLES)
        suffix = ["II", "III", "IV", "V", "Revisited", "Renewed", "Reflected", "Remembered"][len(titles) % 8]
        new_title = f"{base} {suffix}"
        if new_title not in titles:
            titles.append(new_title)
    
    # Shuffle both lists
    random.seed(42)  # For reproducibility
    random.shuffle(titles)
    random.shuffle(summaries)
    
    # Assign unique title and summary to each image
    for i, (img_id, data) in enumerate(feeds.items()):
        data['title'] = titles[i % len(titles)]
        data['summary'] = summaries[i % len(summaries)]
    
    # Save updated feeds
    with open('feeds.json', 'w') as f:
        json.dump(feeds, f, indent=2)
    
    # Verify uniqueness
    new_titles = [v['title'] for v in feeds.values()]
    new_summaries = [v['summary'] for v in feeds.values()]
    
    print(f"\nAfter update:")
    print(f"Unique titles: {len(set(new_titles))}")
    print(f"Unique summaries: {len(set(new_summaries))}")
    
    # Check for any remaining duplicates
    from collections import Counter
    title_counts = Counter(new_titles)
    summary_counts = Counter(new_summaries)
    
    title_dups = [(t, c) for t, c in title_counts.items() if c > 1]
    summary_dups = [(s, c) for s, c in summary_counts.items() if c > 1]
    
    if title_dups:
        print(f"\nRemaining duplicate titles: {len(title_dups)}")
        for t, c in title_dups[:5]:
            print(f"  '{t}': {c}x")
    else:
        print("\n✓ All titles are unique!")
        
    if summary_dups:
        print(f"\nRemaining duplicate summaries: {len(summary_dups)}")
        for s, c in summary_dups[:5]:
            print(f"  '{s}': {c}x")
    else:
        print("✓ All summaries are unique!")

if __name__ == "__main__":
    generate_unique_feeds()
